* .travis.yml: fix

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,15 +1,10 @@
 language: emacs-lisp
-env:
-  matrix:
-    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
-before_install:
-  # Install Emacs
-  - if [ -n "$EMACS_PPA" ]; then
-  sudo add-apt-repository -y "$EMACS_PPA";
-  fi
+
 install:
+  - sudo add-apt-repository -y
   - sudo apt-get update -qq
-  - sudo apt-get install --force-yes -qq "$EMACS"
-  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true # OK to fail
+  - sudo apt-get install --force-yes -qq emacs-snapshot
+  - sudo apt-get install --force-yes -qq emacs-snapshot || true # OK to fail
+
 script:
   ./run-travis.sh
