* .travis.yml: update ppa repo

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,16 +1,18 @@
 language: emacs-lisp
 env:
   matrix:
-    - EMACS=emacs-snapshot
+    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
+  matrix:
+    allow_failures:
+      - env: EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
 before_install:
-    - if [ "$EMACS" = 'emacs-snapshot' ]; then
-      sudo add-apt-repository -y ppa:cassou/emacs &&
-      sudo apt-get update -qq;
-      fi
+  # Install Emacs
+  - if [ -n "$EMACS_PPA" ]; then
+  sudo add-apt-repository -y "$EMACS_PPA";
+  fi
 install:
-    - if [ "$EMACS" = 'emacs-snapshot' ]; then
-      sudo apt-get install -qq
-          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot texinfo;
-      fi
+  - sudo apt-get update -qq
+  - sudo apt-get install --force-yes -qq "$EMACS"
+  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true # OK to fail
 script:
   ./run-travis.sh
